const data = {
	info:{
		iconSrc:'img/log1.jpg',
		name:'何 纯 容',
		level:'二级',
		age:'41岁',
		address:'重庆',
		years:'9年经验',
		type:'月嫂、育儿嫂、催乳师、产后修复师、小二推拿师',
		education:'本科',
		nation:'汉族',
		zodiac:'猪',
		constellation:'处女座',
		height:'161cm',
		weight:'65kg',
		gender:'女',
		marital:'已婚',
		language:'普通话标准',
		home:'住家',
		introduce:'从幼儿教师转行做月嫂，教养结合，陪伴婴幼儿走好人生第一步',
		skill:'中餐、家教、营养、月子餐、开奶、催乳、早教、煲汤、亲子阅读、营养配餐、营养教养培养、蒸菜、收纳、抚触、被动操、排气操、产后修复、婴幼儿护理、心理辅导、恶露观察、肚脐护理、黄疸分辨、辅食添加、早教开发',
	},
	//生活工作照
	lifePhotoList:[
		'lifePhoto/1.jpg',
		'lifePhoto/2.jpg',
		'lifePhoto/3.jpg',
		'lifePhoto/4.jpg',
		'lifePhoto/5.jpg',
		'lifePhoto/6.jpg',
		'lifePhoto/7.jpg',
		'lifePhoto/8.jpg',
		'lifePhoto/9.jpg',
		'lifePhoto/10.jpg',
		'lifePhoto/11.jpg'
	],
	//资格证照片
	certificationPhotoList:[
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg',
		'img/photo.jpg'
	],
	//月子餐照片
	mealPhotoList:[
		'mealPhoto/1.jpg',
		'mealPhoto/2.jpg',
		'mealPhoto/3.jpg',
		'mealPhoto/4.jpg',
		'mealPhoto/5.jpg',
		'mealPhoto/6.jpg',
		'mealPhoto/7.jpg',
		'mealPhoto/8.jpg',
		'mealPhoto/9.jpg',
		'mealPhoto/10.jpg',
		'mealPhoto/11.jpg',
		'mealPhoto/12.jpg',
		'mealPhoto/13.jpg',
		'mealPhoto/14.jpg',
		'mealPhoto/15.jpg',
		'mealPhoto/16.jpg',
		'mealPhoto/17.jpg',
		'mealPhoto/18.jpg',
		'mealPhoto/19.jpg',
		'mealPhoto/20.jpg',
		'mealPhoto/21.jpg',
		'mealPhoto/22.jpg',
		'mealPhoto/23.jpg',
		'mealPhoto/24.jpg',
		'mealPhoto/25.jpg',
		'mealPhoto/26.jpg',
		'mealPhoto/27.jpg',
		'mealPhoto/28.jpg',
		'mealPhoto/29.jpg',
		'mealPhoto/30.jpg',
		'mealPhoto/31.jpg',
		'mealPhoto/32.jpg',
		'mealPhoto/33.jpg',
		'mealPhoto/34.jpg',
		'mealPhoto/35.jpg',
		'mealPhoto/36.jpg',
		'mealPhoto/37.jpg',
		'mealPhoto/38.jpg',
		'mealPhoto/39.jpg',
		'mealPhoto/40.jpg',
		'mealPhoto/41.jpg',
		'mealPhoto/42.jpg'
	],
	workExperience:[
		{
			timeq:'2018年03月-至今',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2015年03月-2018年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2010年03月-2015年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2004年07月-2010年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2001年03月-2004年06月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'1988年07月-2001年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		}
	]
}
export default data;
