const data = {
	info:{
		iconSrc:'img/log1.png',
		name:'何 纯 容',
		level:'二级',
		age:'41岁',
		address:'重庆',
		years:'9年经验',
		type:'月嫂、育儿嫂、催乳师、产后修复师、小二推拿师',
		education:'本科',
		nation:'汉族',
		zodiac:'猪',
		constellation:'处女座',
		height:'161cm',
		weight:'65kg',
		gender:'女',
		marital:'已婚',
		language:'普通话标准',
		home:'住家',
		introduce:'从幼儿教师转行做月嫂，教养结合，陪伴婴幼儿走好人生第一步',
		skill:'中餐、家教、营养、月子餐、开奶、催乳、早教、煲汤、亲子阅读、营养配餐、营养教养培养、蒸菜、收纳、抚触、被动操、排气操、产后修复、婴幼儿护理、心理辅导、恶露观察、肚脐护理、黄疸分辨、辅食添加、早教开发',
	},
	//生活工作照
	lifePhotoList:[
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png'
	],
	//资格证照片
	certificationPhotoList:[
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png'
	],
	//月子餐照片
	mealPhotoList:[
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png',
		'img/photo.png'
	],
	workExperience:[
		{
			timeq:'2018年03月-至今',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2015年03月-2018年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2010年03月-2015年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2004年07月-2010年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'2001年03月-2004年06月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		},{
			timeq:'1988年07月-2001年03月',
			work:'1988年毕业于涪陵幼师，在南川南平幼儿园、中心幼儿园从事幼儿教育工作'
		}
	]
}
export default data;
